@id=00000000-0000-0000-0000-000000000000

PUT http://localhost:5172/TwitterInfos/{{id}}
Content-Type: application/json

{
    "name": "Joe Twitter Info",
    "description": "Info pulled for JH code challenge",
    "duration": "00:00:01"
}